// <auto-generated />
using HappiAdventure.Application.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappiAdventure.Application.Migrations
{
    [DbContext(typeof(HappiAdventureDbContext))]
    partial class HappiAdventureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityPlace", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("integer")
                        .HasColumnName("activities_id");

                    b.Property<int>("PlacesId")
                        .HasColumnType("integer")
                        .HasColumnName("places_id");

                    b.HasKey("ActivitiesId", "PlacesId")
                        .HasName("pk_place_activities");

                    b.HasIndex("PlacesId")
                        .HasDatabaseName("ix_place_activities_places_id");

                    b.ToTable("PlaceActivities", (string)null);
                });

            modelBuilder.Entity("HappiAdventure.Application.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_activities_code");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("HappiAdventure.Application.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PriceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("price_level");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_places_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_places_name");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("ActivityPlace", b =>
                {
                    b.HasOne("HappiAdventure.Application.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_activities_activities_activities_id");

                    b.HasOne("HappiAdventure.Application.Models.Place", null)
                        .WithMany()
                        .HasForeignKey("PlacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_activities_places_places_id");
                });
#pragma warning restore 612, 618
        }
    }
}
